<?php
    /** @var \DynamicYield\Integration\Helper\Data $helper */
    $helper = $this->helper(\DynamicYield\Integration\Helper\Data::class);
?>

<script>
    var require = {
        "baseUrl": "<?php echo $block->getViewFileUrl('/') ?>"
    };
</script>

<?php if ($helper->isEnabled()) : ?>
    <?php if ($helper->getJsIntegration()) : ?>
        <script type="text/javascript">// <![CDATA[
            window.DY = window.DY || {}; DY.recommendationContext = <?php echo json_encode($helper->getCurrentContext()); ?>;
            // ]]>
        </script>
        <?php foreach ($helper->getJsIntegration() as $item) : ?>
            <script type="text/javascript" src="<?php echo $item ?>"></script>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>